### ISSUE TITLE
Build constraints and bounds in the same function

### ISSUE THREAD

**Issue by PierreMartinon** [control-toolbox/CTDirect.jl#10]
Probably more compact than using two similar functions.

**Comment by PierreMartinon** [comment]
Since it seems we will push the functions for objective and constraints to toplevel (in order to recompute the constraints at the solution), we may put the computation of the bounds in the constraints function after all. At function start set a boolean indicator based on the bounds fields in the struct being defined or not, and perform bound computation / field update if needed. This should allow to detect the first call (use a print to check that bounds are not recomputed during optimization)

**Comment by PierreMartinon** [comment]
Note: maybe use a similar factorization and merge the functions that build the initial guess and the variables bounds ?

**Comment by ocots** [comment]
This discussion is very interesting about calling ones a function which is shared by the objective and the constraints: https://github.com/orgs/JuliaSmoothOptimizers/discussions/34

**Comment by PierreMartinon** [comment]
Yes, this is a different question, when F and C share a significant part of the computations. I remember a solver who handled a single function eval_fg precisely for this. In ipopt you can *try* to use the 'new_x' parameter that is supposed to tell you if the NLP variables have changed since the last call, but this is not exactly know territory if I remember correctly.

For the issue here, the aim is to reduce code duplication, since the vectors for the constraints C(X) and the corresponding lower an upper bounds have the same layout, so we use the same kind of loops in both. I think we can add the computation of the bounds in the constraints function, with a proper flag so that it is only executed at the first call before the optimization starts, with subsequent calls only computing C(X) as usual. It will also make any future changes to the layout of the constraints easier, since there will be less code to update.

**Comment by PierreMartinon** [comment]
Need some profiling first.

**Comment by PierreMartinon** [comment]
A first step would be to use more subroutines in the two functions, to minimize duplicate code and make it easier to use different discretization schemes later.

**Comment by PierreMartinon** [comment]
Some refactoring done in constraints / bounds handling.
Further unification with variable box constraints seems complicated due to the 'elastic' format of the variables bounds (optional components, free ordering)
