### ISSUE TITLE
Reverse over forward for Hessians

### ISSUE THREAD

**Issue by jbcaillau** [control-toolbox/CTDirect.jl#117]
@PierreMartinon try to use `CTBase.jl` possibility to change AD backends and compute Hessians with reverse mode (over Forward for gradients).

See also: [this issue](https://github.com/orgs/control-toolbox/discussions/47#discussioncomment-9836232)

**Comment by amontoison** [comment]
I checked where you use ADNLPModels.jl and it seems that you already use optimized AD backends:
https://github.com/control-toolbox/CTDirect.jl/blob/ace7e87a1cc12cb62cd54c773c80609f59908652/src/solve.jl#L37

**Comment by jbcaillau** [comment]
@amontoison you mean that the default is this combination (= reverse after forward)?

> I checked where you use ADNLPModels.jl and it seems that you already use optimized AD backends:
> 
> https://github.com/control-toolbox/CTDirect.jl/blob/ace7e87a1cc12cb62cd54c773c80609f59908652/src/solve.jl#L37
> 
> 
> The optimized backend for Hessian is "Forward over Reverse".

**Comment by amontoison** [comment]
@jbcaillau When you create an ADNLPModel, you use the kwarg `backend = :optimized`, so you use these following backends:
https://github.com/JuliaSmoothOptimizers/ADNLPModels.jl/blob/main/src/predefined_backend.jl#L16

**Comment by jbcaillau** [comment]
Only in `CTDirect.jl` I think. Copying @PierreMartinon and @ocots
