### ISSUE TITLE
Initial guess part update

### ISSUE THREAD

**Issue by PierreMartinon** [control-toolbox/CTDirect.jl#141]
Steps for the CTDirect / CTBase updates
- [x] 1. Merge v0.9.0 with local init into main
- [x] 2. Then comment local init and its export, and make release from this branch; set as pre production release
- [x] 3. Then update CTBase and test 0.9.0
- [x] 4. Release updated CTBase
- [x] 5. Update CTBase requirement, delete local init, merge into main and release 0.9.1 normally

**Comment by jbcaillau** [comment]
@PierreMartinon looks like this is almost done, no?

Regarding `HSL.jl`, @amontoison confirms it is very light (everything is in the `dll`) so this can indeed be included (= `using HSL`) in `CTDirect.jl`, should be harmful on load time.

**Comment by PierreMartinon** [comment]
Yup, done and done

**Comment by jbcaillau** [comment]
@PierreMartinon any clue welcome on https://github.com/control-toolbox/CTDirect.jl/issues/69#issuecomment-2208654289

**Comment by PierreMartinon** [comment]
> @PierreMartinon any clue welcome on [#69 (comment)](https://github.com/control-toolbox/CTDirect.jl/issues/69#issuecomment-2208654289)

Haven't tried the HSL option yet. I'll do this when restarting the performance/benchmarking part.

**Comment by amontoison** [comment]
> @PierreMartinon looks like this is almost done, no?
> 
> Regarding `HSL.jl`, @amontoison confirms it is very light (everything is in the `dll`) so this can indeed be incluhttps://docs.github.com/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntaxded (= `using HSL`) in `CTDirect.jl`, should be harmful on load time.

HSL.jl only has HSL_jll.jl as dependency so it's very light.
You can only depend on HSL_jll.jl if you want but you will not gain a lot and you need to copy this Julia function here:
https://github.com/JuliaSmoothOptimizers/HSL.jl/blob/main/src/C/libhsl.jl#L1

The main advantage of using HSL.jl is that it takes care of loading an LP64 BLAS / LAPACK for you with the function `__init__`
https://github.com/JuliaSmoothOptimizers/HSL.jl/blob/main/src/HSL.jl#L16

But in your case you also depend on Ipopt.jl and I implemented the same init function.
