### ISSUE TITLE
Adjoint (dynamics multipliers) parsing

### ISSUE THREAD

**Issue by jbcaillau** [control-toolbox/CTDirect.jl#184]
@PierreMartinon As discussed: probable shift in `parse_DOCP_solution_dual` when retrieving the multipliers associated with the dynamics (= adjoints). Bug seem to be activated for problems with nonlinear constraints (= not mere boxes on slices of state / control). See for instance this variant of Goddard that, contrary to [this one](https://control-toolbox.org/OptimalControl.jl/stable/tutorial-iss.html), has a such a nonlinear constraint: https://github.com/control-toolbox/BVP-DAE/issues/1#issuecomment-2246348545

Similar behaviour for these other projects that also have nonlinear (control or mixed) constraints:
@alesiagr https://github.com/mctao-inria/sail-therm
@PhysicDev https://github.com/PhysicDev/McTao_lunar_solar_sail

**Comment by jbcaillau** [comment]
@PierreMartinon in the current below, compared to the previous tags, I don't see where you would skip the multipliers associated with constraints other than the dynamics (*e.g.* state constraints) in order to retrieve only the dynamics:
```julia
"""
$(TYPEDSIGNATURES)

Recover OCP costate from DOCP multipliers
"""
# +++todo: parse multipliers for the path and boundary constraints (use tuples)
function parse_DOCP_solution_dual(docp, multipliers)

    # constraints, costate and constraints multipliers
    N = docp.dim_NLP_steps
    P = zeros(N, docp.dim_NLP_x)
    
    if !isnothing(multipliers)
        index = 1
        for i in 1:N
            # state equation multiplier for costate
            P[i,:] = multipliers[index:index+docp.dim_NLP_x-1]
            index = index + docp.dim_NLP_x
        end
    end

    return P
end
```

**Comment by PierreMartinon** [comment]
@jbcaillau  
Should be fixed in 0.9.6, can you try updating ?

**Comment by alesiagr** [comment]
J'arrive pas à update la version 0.9.6, j'ai tjrs la 0.9.4. Sinon je pourrais tester de suite

**Comment by jbcaillau** [comment]
👍🏽 @PierreMartinon vu pour la ligne ci-dessous, je teste
https://github.com/control-toolbox/CTDirect.jl/blob/d2321e293ae43d0187e53c901432f5916b902247/src/solution.jl#L46

**Comment by jbcaillau** [comment]
@PierreMartinon CTDirect 0.9.6 now available. Latency? Anyway, seems much better 🙂 @ocots @alesiagr 
![IMG_3362](https://github.com/user-attachments/assets/1ce09ae5-dbeb-4c6a-9529-50200b26f1ec)

**Comment by alesiagr** [comment]
BINGO! @jbcaillau @PierreMartinon @ocots  Merci 🙏🏼
Qu'ils sont beaux ces adjoints quand ils oscillent pas 🥹

**Comment by PierreMartinon** [comment]
Il faudra que je complete les tests pour le parsing de solution, verifier qu'on recupere bien ce qu'il faut. Actuellement on ne teste que l'objectif.

**Comment by ocots** [comment]
Top si on peut corriger ce bug. Il faudra relancer les simulations avec Paul.

**Comment by ocots** [comment]
Je ne sais pas si ça peut aider mais il y a un lien entre l'adjoint du direct et de l'indirect dans le cas de contraintes d'états dans ce papier : https://inria.hal.science/hal-01367918

Il y a cette proposition page 15 

<img width="997" alt="Capture d’écran 2024-07-25 à 21 36 40" src="https://github.com/user-attachments/assets/aa6f7901-237c-481b-b5b7-ae5a27e93b9f">

et cette figure juste après

<img width="1180" alt="Capture d’écran 2024-07-25 à 21 36 21" src="https://github.com/user-attachments/assets/2a1fd04f-f130-4c70-b481-52efee875f36">

**Comment by alesiagr** [comment]
Je sais pas si ça s'adressait à moi ton message mais merci @ocots  :D

**Comment by ocots** [comment]
Plutôt à @PierreMartinon et @jbcaillau mais tu peux regarder 😀

**Comment by jbcaillau** [comment]
> Top si on peut corriger ce bug. Il faudra relancer les simulations avec Paul.

@PierreMartinon has corrected. Leaving the issue open so that we remember to add the relevant unitary test in CTDirect.

**Comment by jbcaillau** [comment]
@PierreMartinon still missing unit tests before closing, right?

**Comment by PierreMartinon** [comment]
> @PierreMartinon still missing unit tests before closing, right?

Yes. Ideally we would test the closeness of the interpolated trajectory and costate to a known functional solution (evaluate both on a given time grid then use *isapprox*) . Does anyone have a basic problem with simple expressions for x,u,p ?

**Comment by jbcaillau** [comment]
@PierreMartinon is our [basic example](https://control-toolbox.org/OptimalControl.jl/stable/tutorial-basic-example.html) OK? (One of the adjoint is not constant.)

**Comment by ocots** [comment]
> @PierreMartinon is our [basic example](https://control-toolbox.org/OptimalControl.jl/stable/tutorial-basic-example.html) OK? (One of the adjoint is not constant.)

There is a problem here : https://control-toolbox.org/OptimalControl.jl/stable/tutorial-double-integrator.html

**Comment by PierreMartinon** [comment]
> > @PierreMartinon is our [basic example](https://control-toolbox.org/OptimalControl.jl/stable/tutorial-basic-example.html) OK? (One of the adjoint is not constant.)
> 
> There is a problem here : [control-toolbox.org/OptimalControl.jl/stable/tutorial-double-integrator.html](https://control-toolbox.org/OptimalControl.jl/stable/tutorial-double-integrator.html)

@ocots, the second one does not converge on the page :D

**Comment by ocots** [comment]
> > > @PierreMartinon is our [basic example](https://control-toolbox.org/OptimalControl.jl/stable/tutorial-basic-example.html) OK? (One of the adjoint is not constant.)
> > 
> > 
> > There is a problem here : [control-toolbox.org/OptimalControl.jl/stable/tutorial-double-integrator.html](https://control-toolbox.org/OptimalControl.jl/stable/tutorial-double-integrator.html)
> 
> Ok, I'll take the double integrator ! @ocots, the second one does not converge on the page :D

Do you understand why?

**Comment by PierreMartinon** [comment]
I'll have a look as soon as I can get CTBase 0.12 (there is usually some latency)

**Comment by ocots** [comment]
> I'll have a look as soon as I can get CTBase 0.12 (there is usually some latency)

It is ready. You can get it whenever you want.

**Comment by PierreMartinon** [comment]
When retesting locally the problem converges.
![sol](https://github.com/user-attachments/assets/669f5ce9-3d61-45f5-905e-c6a4234d030a)

Let's try to rebuild the doc and check ?

**Comment by PierreMartinon** [comment]
On the other hand, tests for state, control and costate added and OK for the double integrator

**Comment by ocots** [comment]
It converged with `100` points bu not with `200`. Here how many do you have?

**Comment by PierreMartinon** [comment]
New default in CTDirect is 250, so 250 probably

**Comment by jbcaillau** [comment]
> New default in CTDirect is 250, so 250 probably

@PierreMartinon 👍🏽

NB. probably safer to use double integrator with $L^2$ cost (no issue of convergence, whatever the grid size)
