### ISSUE TITLE
Use inplace when building the NLP model

### ISSUE THREAD

**Issue by jbcaillau** [control-toolbox/CTDirect.jl#188]
@PierreMartinon @ocots @gergaud it is actually possible but takes a rather deep revision of CTBase, abstract / fun API: 
- an OCP could be declared `inplace` when created, requesting then that every function providing dyn / cost / constraints) be inplace
- from the abstract syntax, it is possible to generate inplace code only
- lot of memory saving expected, I suppose
- in the "building a better NLP" line, I think (but might be wrong) that https://github.com/control-toolbox/CTDirect.jl/issues/183#issuecomment-2268306797 is a higher priority

On a side note: more and more, I think that the functional API should be kept for internal use only.

**Comment by jbcaillau** [comment]
> * in the "building a better NLP" line, I think (but might be wrong) that [Pass sparse structure of constraints to NLPModels #183 (comment)](https://github.com/control-toolbox/CTDirect.jl/issues/183#issuecomment-2268306797) is a higher priority

@amontoison your opinion on top priority for a better NLP (performance improvement) between (i) passing the sparse structure and (ii) going fully inplace?

**Comment by amontoison** [comment]
> > * in the "building a better NLP" line, I think (but might be wrong) that [Pass sparse structure of constraints to NLPModels #183 (comment)](https://github.com/control-toolbox/CTDirect.jl/issues/183#issuecomment-2268306797) is a higher priority
> 
> @amontoison your opinion on top priority for a better NLP (performance improvement) between (i) passing the sparse structure and (ii) going fully inplace?

In-place (ii) is very important because memory allocations are expensive and you will also remove some allocations in the AD so you will have a speed-up in different part of the code.
(i) is just a one-shot gain speed-up at the creation of your NLP model.

You can work on both but the priority is higher on (ii).

**Comment by jbcaillau** [comment]
> > > * in the "building a better NLP" line, I think (but might be wrong) that [Pass sparse structure of constraints to NLPModels #183 (comment)](https://github.com/control-toolbox/CTDirect.jl/issues/183#issuecomment-2268306797) is a higher priority
> > 
> > 
> > @amontoison your opinion on top priority for a better NLP (performance improvement) between (i) passing the sparse structure and (ii) going fully inplace?
> 
> In-place (ii) is very important because memory allocations are expensive and you will also remove some allocations in the AD part so you will have a speed-up in different part of the code.
> 
> (i) is just a one-shot gain speed-up at the creation of your NLP model.
> 
> You can work on both but the priority is higher on (ii).

👍🏽 thanks for the insight. priority on (ii), then.

**Comment by jbcaillau** [comment]
@jbcaillau For the record:
```julia
julia> foo!(y, x) = begin
       y[:] .= x
       return 
       end
foo! (generic function with 1 method)

julia> y = [0]; foo!(y, 3); y
1-element Vector{Int64}:
 3

julia> y = [0]; foo!(y, [3]); y
1-element Vector{Int64}:
 3
```

**Comment by jbcaillau** [comment]
Related issue: https://github.com/control-toolbox/CTBase.jl/issues/232

**Comment by jbcaillau** [comment]
@PierreMartinon PR merged https://github.com/control-toolbox/CTBase.jl/pull/271 up to you 🤞🏾!

**Comment by ocots** [comment]
> @PierreMartinon PR merged https://github.com/control-toolbox/CTBase.jl/pull/271 up to you 🤞🏾!

Need a new release. Y must be updated.

**Comment by jbcaillau** [comment]
> > @PierreMartinon PR merged [control-toolbox/CTBase.jl#271](https://github.com/control-toolbox/CTBase.jl/pull/271) up to you 🤞🏾!
> 
> Need a new release. Y must be updated.

✅ @PierreMartinon you can use  CTBase.jl v0.14.0

**Comment by PierreMartinon** [comment]
ok, thanks !

**Comment by jbcaillau** [comment]
@PierreMartinon attaching allocation sizes with the current out of place code on the benchmark created by @0Yassine0 https://github.com/0Yassine0/COTS.jl/issues/24#issuecomment-2343573263

[Model_Benchmark_TTonly_file.pdf](https://github.com/user-attachments/files/16970922/Model_Benchmark_TTonly_file.pdf)

**Comment by jbcaillau** [comment]
PS. @PierreMartinon @0Yassine0 note that definition such the dynamics in the problem below (source [here](https://github.com/control-toolbox/OptimalControlProblems.jl/blob/main/ext/OptimalControlModels/cart_pendulum.jl)) will not generate in place code; the dynamics actually needs to be "inlined" inside `@def`. See also https://github.com/control-toolbox/CTBase.jl/issues/292 

![IMG_3529](https://github.com/user-attachments/assets/20200d9b-4944-4f79-9462-d2a44428e205)

**Comment by jbcaillau** [comment]
@PierreMartinon any progress?

**Comment by PierreMartinon** [comment]
@jbcaillau @amontoison Still hunting for type unstabilities and allocations, but at least the getters are fine now !

Back to the whole inplace aspect, I am starting to wonder if it will change much: the function for the NLP constraints has already been inplace since basically the beginning, and the OCP functions are typically used as:
- `c[i:j] = ocp.some_constraint(...)` for all the different constraints kinds
- `c[i:j] = x_i_plus_1 - (x_i + h_i * ocp.dynamics(...))` for the dynamics (here I wrote the formula for explicit Euler but the general form is the same for other discretizations)

Seeing this, the destination for the OCP functions is already allocated in c, so do we really benefit from them being inplace ? Inplace version currently looks like
- `ocp.some_constraints(view c[i:j], ...)`
- for the dynamics it's a bit convoluted
`ocp.dynamics(view c[i:j], ...)
c[i:j] = - h_i * c[i:j] - x_i + x_i_plus_1`

Am I missing something ?

**Comment by PierreMartinon** [comment]
It's just that I seem to get the same allocations for the inplace and out of place versions -_-
But maybe this is due to the more general type problem with the functions thmeselves. Or I did not properly write the inplace constraints.

Inplace: 15 + 15 + 18 allocs
```
    144            .          .               # 2. path constraints 
    145            .          .               # Notes on allocations:.= seems similar 
    146            .          .               if docp.dim_u_cons > 0 
    147            .          .                   if docp.is_inplace 
    148            .         15                       docp.control_constraints[2]((@view c[offset+1:offset+docp.dim_u_cons]),ti, ui, v) 
    149            .          .                   else 
    150            .          .                       c[offset+1:offset+docp.dim_u_cons] = docp.control_constraints[2](ti, ui, v) 
    151            .          .                   end 
    152            .          .               end 
    153            .          .               if docp.dim_x_cons > 0  
    154            .          .                   if docp.is_inplace 
    155            .         15                       docp.state_constraints[2]((@view c[offset+docp.dim_u_cons+1:offset+docp.dim_u_cons+docp.dim_x_cons]),ti, xi, v) 
    156            .          .                   else 
    157            .          .                       c[offset+docp.dim_u_cons+1:offset+docp.dim_u_cons+docp.dim_x_cons] = docp.state_constraints[2](ti, xi, v) 
    158            .          .                   end 
    159            .          .               end 
    160            .          .               if docp.dim_mixed_cons > 0  
    161            .          .                   if docp.is_inplace 
    162            .         18                       docp.mixed_constraints[2]((@view c[offset+docp.dim_u_cons+docp.dim_x_cons+1:offset+docp.dim_u_cons+docp.dim_x_cons+docp.dim_mixed_cons]), ti, xi, ui, v) 
    163            .          .                   else 
    164            .          .                       c[offset+docp.dim_u_cons+docp.dim_x_cons+1:offset+docp.dim_u_cons+docp.dim_x_cons+docp.dim_mixed_cons] = docp.mixed_constraints[2](ti, xi, ui, v) 
    165            .          .                   end 
    166            .          .               end 
```

Out of place: 16 + 17 + 20 allocs. It is a bit less, but not much.
```
    144            .          .               # 2. path constraints 
    145            .          .               # Notes on allocations:.= seems similar 
    146            .          .               if docp.dim_u_cons > 0 
    147            .          .                   if docp.is_inplace 
    148            .          .                       docp.control_constraints[2]((@view c[offset+1:offset+docp.dim_u_cons]),ti, ui, v) 
    149            .          .                   else 
    150            .         16                       c[offset+1:offset+docp.dim_u_cons] = docp.control_constraints[2](ti, ui, v) 
    151            .          .                   end 
    152            .          .               end 
    153            .          .               if docp.dim_x_cons > 0  
    154            .          .                   if docp.is_inplace 
    155            .          .                       docp.state_constraints[2]((@view c[offset+docp.dim_u_cons+1:offset+docp.dim_u_cons+docp.dim_x_cons]),ti, xi, v) 
    156            .          .                   else 
    157            .         17                       c[offset+docp.dim_u_cons+1:offset+docp.dim_u_cons+docp.dim_x_cons] = docp.state_constraints[2](ti, xi, v) 
    158            .          .                   end 
    159            .          .               end 
    160            .          .               if docp.dim_mixed_cons > 0  
    161            .          .                   if docp.is_inplace 
    162            .          .                       docp.mixed_constraints[2]((@view c[offset+docp.dim_u_cons+docp.dim_x_cons+1:offset+docp.dim_u_cons+docp.dim_x_cons+docp.dim_mixed_cons]), ti, xi, ui, v) 
    163            .          .                   else 
    164            .         20                       c[offset+docp.dim_u_cons+docp.dim_x_cons+1:offset+docp.dim_u_cons+docp.dim_x_cons+docp.dim_mixed_cons] = docp.mixed_constraints[2](ti, xi, ui, v) 
    165            .          .                   end 
    166            .          .               end 
```

**Comment by PierreMartinon** [comment]
Hi @ocots, @jbcaillau 
When do we want to drop support for out-of-place OCPs ?

This means that we only accept
- abstract definitions (preferred way)
- functional definitions written inplace (with inplace=true)
Former out-of-place functional OCPs would need to be rewritten in either form. I've done it for `CTDirect`.

NB. we could make inplace the default for functional OCPs also, and eventually remove out-of-place OCPs completely at some point ?

**Comment by jbcaillau** [comment]
> Dropped out-of-place support in current main branch, can be reinstated if needed.

@PierreMartinon fine. the idea is indeed to
- leverage abstract definitions that use the expressions provided by the user to generate inplace functions
- keep functional definitions through refurbished setters (`time!`, `control!`, *etc.*) as is currently being done by @ocots, with inplace everywhere (and unique signatures: no more scalar / vector, autonomous / nonautonomous, variable / fixed combinations)
