### ISSUE TITLE
Default values

### ISSUE THREAD

**Issue by ocots** [control-toolbox/CTDirect.jl#195]
Replace default values by the ones defined in `CTBase.jl` when the new release is released: https://github.com/control-toolbox/CTBase.jl/issues/220.

https://github.com/control-toolbox/CTDirect.jl/blob/a9ae483a57382d44dba0612af914d78275fd6d7a/src/CTDirect.jl#L17

**Comment by PierreMartinon** [comment]
By the way, how do we organize the default values ? I find it a bit confusing to redefine default values at multiple levels.

We could
- define everything in CTBase since every package is supposed to use it anyway
- define the 'generic' ones in CTBase and the 'specific' ones (such as the grid size above) in their related packages ?

**Comment by ocots** [comment]
Can you take a look at the end of this comment: https://github.com/control-toolbox/CTBase.jl/pull/222#issuecomment-2272959642

With `200` there is a problem on an example.

**Comment by ocots** [comment]
You are right for the default values. We already do that here: https://github.com/control-toolbox/CTFlows.jl/blob/main/src/default.jl

I will just add a file with the specific default values with docstrings in `CTDirect.jl`.

**Comment by ocots** [comment]
To keep track:

```julia
# ------------------------------------------------------------------------------------
# Direct methods

"""
$(TYPEDSIGNATURES)

Used to set the default grid size.
The default value is `100`.
"""
__grid_size_direct() = 100

"""
$(TYPEDSIGNATURES)

Used to set the default time grid.
The default value is `nothing`.
"""
__time_grid_direct() = nothing

"""
$(TYPEDSIGNATURES)

Used to set the default tolerance.
The default value is `1e-8`.
"""
__tolerance_direct() = 1e-8

"""
$(TYPEDSIGNATURES)

Used to set the default maximum of iterations.
The default value is `1000`.
"""
__max_iterations_direct() = 1000

"""
$(TYPEDSIGNATURES)

Used to set the default linear solver.
The default value is `:ma57`.
"""
__linear_solver_direct() = :ma57
```

and

```julia
    @testset "Default value for direct solver" begin
        @test CTBase.__grid_size_direct() isa Integer
        @test isnothing(CTBase.__time_grid_direct())
        @test CTBase.__tolerance_direct() < 1
        @test CTBase.__max_iterations_direct() isa Integer
        @test CTBase.__linear_solver_direct() isa Symbol
    end
```

**Comment by PierreMartinon** [comment]
@ocots I can add the default.jl file and tests
