### ISSUE TITLE
Put algorithms variable inside the available_methods function

### ISSUE THREAD

**Issue by ocots** [control-toolbox/CTDirect.jl#196]
Actually, I don't know why I dit it like that but the construction of the list of methods in the `algorithms` variable could be put inside the `available_methods` function and then we do not care about the name of the variable.

https://github.com/control-toolbox/CTDirect.jl/blob/8e27827b36d43e09aa0e62365420a3b089ea3da3/src/solve.jl#L4

**Comment by PierreMartinon** [comment]
Done
