### ISSUE TITLE
New ExtensionError

### ISSUE THREAD

**Issue by ocots** [control-toolbox/CTDirect.jl#197]
https://github.com/control-toolbox/CTDirect.jl/blob/0d38ab5f91aafe7d50a85d4f7f548fabd43891a6/src/solve.jl#L72

From `CTBase.jl` version `v0.12.0`, this must be replaced by:

```julia
throw(ExtensionError(:NLPModelsIpopt))
```

**Comment by PierreMartinon** [comment]
Done
