### ISSUE TITLE
Move default values

### ISSUE THREAD

**Issue by ocots** [control-toolbox/CTDirect.jl#27]
The default values for the direct method from [CTBase.jl](https://github.com/control-toolbox/CTBase.jl/blob/main/src/default.jl) should be moved in the `CTDirect.jl` package.

**Comment by PierreMartinon** [comment]
__grid_size_direct() is now defined in CTDirect

**Comment by joseph-gergaud** [comment]
and rk_method

**Comment by ocots** [comment]
ok!
