### ISSUE TITLE
Initial guess

### ISSUE THREAD

**Issue by joseph-gergaud** [control-toolbox/CTDirect.jl#28]
- [x] Generic initialisation as function of time
- [x] Constant initialisation with optional x_init, u_init, v_init (default to 0.1)
- [x] Warm start ie initialisation from existing solution
- [ ] Initialisation of the co-state variable ?

**Comment by PierreMartinon** [comment]
The only change is when explicitely passing an init to solve().
- old syntax was to pass a single vector containing all constant values
```
x_init = [1.0, 0.1]
u_init = [0.5]
v_init = [2]
solve(..., init=[x_init, u_init, v_init], ...)
```
- new syntax passes an OptimalControlInit
```
x_init = [1.0, 0.1]
u_init = [0.5]
v_init = [2]
solve(..., OptimalControlInit(x_init, u_init, v_init), ...)
```
- in addition to constant intialization we can now have a warm start
```
sol1 = solve(...)
sol2 = solve(..., init=OptimalControlInit(sol1), ...)
``` 

As per our discussion I'll improve the 'constant init' Constructor a bit by making all arguments optional (v_init is optional already) and merge the () constructor with it.
Release will follow.

**Comment by PierreMartinon** [comment]
Put aside multipliers initialization for now due to the questionable benefits observed with Bocop2.
