### ISSUE TITLE
New release of CTBase

### ISSUE THREAD

**Issue by ocots** [control-toolbox/CTDirect.jl#29]
A new release of `CTBase` is available, see [v0.6.0](https://github.com/control-toolbox/CTBase.jl/releases/tag/v0.6.0).

I suggest you, @PierreMartinon and @joseph-gergaud, to include this new version.

You have to update the "compat":

https://github.com/control-toolbox/CTDirect.jl/blob/2df2ba33b43c5a8c9225ec63023203c71952e723/Project.toml#L15

I have made the following changes:

- no getters for the fields of an `OptimalControlModel` anymore
- `state_labels` -> `state_names`
- `control_labels` -> `control_names`
- I have removed some default values that are now directly into the solvers packages

About the getters, you can still define your own getters if you don't want to modify your code. You can include in [CTDirect.jl](https://github.com/control-toolbox/CTDirect.jl/blob/main/src/CTDirect.jl):

```julia
dynamics(ocp::OptimalControlModel) = ocp.dynamics
lagrange(ocp::OptimalControlModel) = ocp.lagrange
mayer(ocp::OptimalControlModel) = ocp.mayer
criterion(ocp::OptimalControlModel) = ocp.criterion
initial_time(ocp::OptimalControlModel) = ocp.initial_time
final_time(ocp::OptimalControlModel) = ocp.final_time
control_dimension(ocp::OptimalControlModel) = ocp.control_dimension
control_labels(ocp::OptimalControlModel) = ocp.control_names
state_dimension(ocp::OptimalControlModel) = ocp.state_dimension
state_labels(ocp::OptimalControlModel) = ocp.state_names
constraints(ocp::OptimalControlModel) = ocp.constraints
```

You have also to update:

https://github.com/control-toolbox/CTDirect.jl/blob/2df2ba33b43c5a8c9225ec63023203c71952e723/src/solution.jl#L45

and

https://github.com/control-toolbox/CTDirect.jl/blob/2df2ba33b43c5a8c9225ec63023203c71952e723/src/solution.jl#L48

**Comment by ocots** [comment]
Sorry, there is also `time_name` which replace `time_label`. Update

https://github.com/control-toolbox/CTDirect.jl/blob/2df2ba33b43c5a8c9225ec63023203c71952e723/src/solution.jl#L43

**Comment by ocots** [comment]
It could be nice to have a new release of ctdirect integrating those changes. You can update the z of x.y.z in the toml or the y if you have added some features or break compat. For the moment we do not touch the x.

Just a usable release would be nice. It is to update then OptimalControl: remove direct shooting (not enough mature compared to direct) and start some doc of examples.

**Comment by PierreMartinon** [comment]
@cots Ok I'll do this from current main (branch RK is not ready to merge yet)

**Comment by ocots** [comment]
The compilation works in the branch `0.2.2` but not the tests. You can fix it and make a PR.

**Comment by PierreMartinon** [comment]
Yes I'm on it, I was waiting for CTProblems.

**Comment by PierreMartinon** [comment]
All problems pass except exponential conso min. Can you check this one and do the PR ?

**Comment by PierreMartinon** [comment]
Ok, this one is getting out of hand -_-
0.2.2 was supposed to be the update of CTBase, and it goes more complicated since CTProblems had changed as well. We need to do this release now and stop adding changes to main (cf the algorithm and description part).

**Comment by ocots** [comment]
I don(t follow you. Everything is fine, no?

Cf. https://github.com/control-toolbox/CTDirect.jl/actions/runs/4628381386/jobs/8187386864

**Comment by ocots** [comment]
I make the new release 0.2.2.

**Comment by ocots** [comment]
New release done.

**Comment by PierreMartinon** [comment]
> I don't follow you. Everything is fine, no?

Yup, but the more changes we make, the more potentially complicated it will be when we merge back main into the ongoing branch for the RK scheme, for instance. Also it took 2 days and several branches/PR for what was basically 3 lines to update, that's not very effective :D

Although I expect the more 'structural' changes will become less frequent as the main code stabilizes, so these updates will hopefully remain simple.

**Comment by ocots** [comment]
Indeed we need to stabilize. It will be more effective with time. We started few months ago.
