### ISSUE TITLE
Benchmark CTDirect vs bocop3

### ISSUE THREAD

**Issue by PierreMartinon** [control-toolbox/CTDirect.jl#31]
Try to do some benchmarks between the two codes (we currently expect CTDirect to be slower due to using derivatives in non-sparse format)
- [x] implement proper trapeze method in bocop3
- [x] implement similar problem goddard
- [x] check initial guess for both codes
- [x] check options for both codes
- [x] CTDirect runs
- [x] bocop3 runs

Differences between the 2 codes:
- [ ] CTDirect currently uses non-sparse derivatives ! (in progress)
- [ ] current version of CTDirect uses a dedicated code for trapeze (the generic RK method similar to bocop3 is in progress)
- [ ] bocop3 currently does not enforce path constraints at the last time step (i.e. final time) (in progress)

**Comment by PierreMartinon** [comment]
Trapeze method +++

**Comment by PierreMartinon** [comment]
Integrator test problem

**Comment by PierreMartinon** [comment]
Goddard test problem

**Comment by PierreMartinon** [comment]
Initial guess

**Comment by PierreMartinon** [comment]
Options

**Comment by PierreMartinon** [comment]
CTDirect runs     Obj        Iter      Cpu
integrator
goddard

bocop3 runs     Obj        Iter      Cpu
integrator
goddard

**Comment by ocots** [comment]
Profiling: https://docs.julialang.org/en/v1/manual/profile/

**Comment by corentinmartinon** [comment]
I dont think there is anything to profile yet. It is well known that using dense matrices for derivatives is quite inefficient.

**Comment by ocots** [comment]
Who is Corentin?

**Comment by PierreMartinon** [comment]
Same as before, I was logged with my other account. I deleted the post

**Comment by jbcaillau** [comment]
Sacré Corentin! Yes, sparse is good.

**Comment by PierreMartinon** [comment]
On second thought I'll probably try some profiling as @ocots mentioned: this huge memory allocation bothers me, I wonder if we have something horrible, such as the constraints vector being allocated at each call !?

**Comment by jbcaillau** [comment]
@PierreMartinon https://github.com/orgs/control-toolbox/discussions/22#discussioncomment-5564197

**Comment by PierreMartinon** [comment]
We'll need to check the getters for state and control variables in particular. If the slices allocate new vectors each time this may be a huge performance issue !

**Comment by ocots** [comment]
Maybe `StaticArrays` also.
