### ISSUE TITLE
Codecov: stop reporting test as failure

### ISSUE THREAD

**Issue by PierreMartinon** [control-toolbox/CTDirect.jl#38]
See for instance https://github.com/control-toolbox/CTDirect.jl/commit/06e2c7cf2673f93b89f3bf3e5a5e6e1e88e85c69
The tests passed but codecov missed its target so we see a failed symbol on the front page.
This is stupid and misleading, how can we prevent codecov from reporting a failure ?

**Comment by ocots** [comment]
We need to add a file like: https://github.com/control-toolbox/CTBase.jl/blob/main/.github/codecov.yml

See also for the common options: https://docs.codecov.com/docs/common-recipe-list

**Comment by PierreMartinon** [comment]
Oh dear I was grumpy that day :D

**Comment by ocots** [comment]
@PierreMartinon Can we close this issue?
