### ISSUE TITLE
Problems and more

### ISSUE THREAD

**Issue by jbcaillau** [control-toolbox/CTDirect.jl#47]
@PierreMartinon @gergaud @ocots 
> Pierre wrote:
> Hello a tous,
>
> Release 0.3.2 avec la mise a jour pour CTBase 0.7.2 (traitement des variables et cas scalaire).

👍🏽 is this release available or not? I am a bit confused with some (old) tests in `CTDirect` that apparently use the old (functional) syntax (= without variables). May be just because they are *old* tests.

> Sur la branche 'init': introduction d'une struct OptimalControlInit (cf src/init.jl) a passer au solve(). Contient essentiellement les dims de x,u,v ainsi que les initialisations t->x(t), t->u(t) et v (pas de variables duales pour le moment). Champ 'info' rappelle le type de constructeur utilise (pourrait etre recupere dans la solution par exemple)

In particular, in `test_goddard.jl` there are four values to initialise instead of five... but the solve works with the current version of the package. *Bref*.

> - cet argument pour solve() est optionnel, si absent on retombe pour le direct sur l'init constante tout a 0.1
>
> - init constante: constructeur OptimalControlInit(x_init, u_init, [v_init])
>
> - warm start: constructeur OptimalControlInit(sol) avec sol::OptimalControlSolution
>
> Les premiers tests (cf simple_integrator et goddard dans test/suite/) semblent ok (note: le goddard converge en fait legerement plus vite avec l'init constant qu'avec le warm start, sachant que pour le moment les variables duales ne sont pas initialisees).
>
> Pour la suite, je ne sais pas si c'est pertinent de faire un merge main et une release si du code doit migrer dans CTBase ? Dites moi ce que vous en pensez !

Please merge! (At least in `develop` if not completely sure.) Nothing to be migrated in `CTBase.jl`, I would say.

For the record, I have added in `test/old/test_goddard.jl` the abstract def and solve below: works fine!
```julia
# goddard, abstract def
const Cd = 310
const Tmax = 3.5
const β = 500
const b = 2
const t0 = 0
r0 = 1
v0 = 0
vmax = 0.1
m0 = 1
mf = 0.6
x0 = [ r0, v0, m0 ]

@def ocp begin

    tf, variable
    t ∈ [ t0, tf ], time
    x ∈ R³, state
    u ∈ R, control

    r = x₁
    v = x₂
    m = x₃

    x(t0) == [ r0, v0, m0 ]
    0  ≤ u(t) ≤ 1
    r0 ≤ r(t) ≤ Inf,     (1)
    0  ≤ v(t) ≤ vmax,    (2)
    mf ≤ m(t) ≤ m0,      (3)

    ẋ(t) == F0(x(t)) + u(t) * F1(x(t))

    r(tf) → max

end

F0(x) = begin
    r, v, m = x
    D = Cd * v^2 * exp(-β*(r - 1))
    F = [ v, -D/m - 1/r^2, 0 ]
    return F
end

F1(x) = begin
    r, v, m = x
    F = [ 0, Tmax/m, -b*Tmax ]
    return F
end

sol = solve(ocp, grid_size=10, print_level=5)
```
![IMG_2169](https://github.com/control-toolbox/CTDirect.jl/assets/62183989/f5235a31-a936-4968-b07f-1b6b1850b45a)

**Comment by PierreMartinon** [comment]
Hey there,
- 0.3.2 appears in ct-registry so you should get it when doing an update
- files in old/ are exactly that, and have not been migrated to the new version yet. Currently only the tests in suite/ are expected to pass.
- nice for the abstract goddard, I'll put it in the new goddard test file
- I can do a merge to main, no problem (the idea was that the init struct would be moved to CTBase at some point). Syntax wise, the only change is when using a constant init: before we passed to solve() a single vector for x,u and v, now we have to call the OptimalControlInit constructor and pass the struct instead. The init argument is still optional so all calls that did not give an explicit init work the same.

**Comment by ocots** [comment]
Is there really 10 steps in the figure of Goddard solution?

**Comment by jbcaillau** [comment]
> Is there really 10 steps in the figure of Goddard solution?

A bit more for this run (100...)

**Comment by PierreMartinon** [comment]
Do you want a release of CTDirect with this part ?

**Comment by jbcaillau** [comment]
Yes, why not? If I get it correctly, the main change concerns initialisation, so this should not break the demo built for this Friday 🤞🏾(basic + goddard, essentially - @ocots and @BaptisteCbl have revised everything, including `Flows`, *etc.*)

> Do you want a release of CTDirect with this part ?

**Comment by PierreMartinon** [comment]
The only change is when explicitely passing an init to solve().
- old syntax was to pass a single vector containing all constant values
```
x_init = [1.0, 0.1]
u_init = [0.5]
v_init = [2]
solve(..., init=[x_init, u_init, v_init], ...)
```
- new syntax passes an OptimalControlInit
```
x_init = [1.0, 0.1]
u_init = [0.5]
v_init = [2]
solve(..., OptimalControlInit(x_init, u_init, v_init), ...)
```
- in addition to constant intialization we can now have a warm start
```
sol1 = solve(...)
sol2 = solve(..., init=OptimalControlInit(sol1), ...)
``` 

As per our discussion I'll improve the 'constant init' Constructor a bit by making all arguments optional (v_init is optional already) and merge the () constructor with it.

**Comment by PierreMartinon** [comment]
Follow to https://github.com/control-toolbox/CTDirect.jl/issues/28
