### ISSUE TITLE
Non uniform (still fixed) time grid for direct method (and direct shooting ?)

### ISSUE THREAD

**Issue by PierreMartinon** [control-toolbox/CTDirect.jl#50]
Allow to pass explicit time grid to solve().

Note: handling a non uniform grid is also a prerequisite of step control mechanisms...

**Comment by PierreMartinon** [comment]
I guess we would pass the time vector to solve() ?

**Comment by jbcaillau** [comment]
@PierreMartinon question related to this [discussion](https://github.com/orgs/control-toolbox/discussions/46#discussioncomment-9578642) with @rand-asswad : is it possible to pass a (possibly non-uniform) grid to `solve`? Should not be a strong change but does not seem available form the [API](https://control-toolbox.org/CTDirect.jl/stable/api.html#CTDirect.solve-Tuple%7BOptimalControlModel,%2520Vararg%7BAny%7D%7D).

**Comment by PierreMartinon** [comment]
I can have a quick look at this, it should be rather simple since the time grid / step is not used at many places in the code.

I guess we can go for an optional argument *time_grid=nothing* for *solve()* ?

**Comment by jbcaillau** [comment]
@ocots ~me too can write *n'importe quoi* then strike through it~ 🤭
> ~Of course it is possible.~

**Comment by jbcaillau** [comment]
@PierreMartinon would be nice to interact with @rand-asswad who might have a nice use case that indeed requires a higher order scheme

> I can have a quick look at this, it should be rather simple since the time grid / step is not used at many places in the code.
> 
> I guess we can go for an optional argument _time_grid_ for _solve()_, with default value nothing for a uniform grid, or the exlicit vector of time steps. Probably add some internal checks for strictly increasing values, and consistency with initial and final times. I would say that providing an explicit time grid would override grid_size if also passed, maybe with a warning (especially if given size does not match the given vector)

**Comment by PierreMartinon** [comment]
This one is the non-uniform grid, not the high order scheme. Are we sleepwriting @jbcaillau ? :D

**Comment by PierreMartinon** [comment]
[Done](https://github.com/control-toolbox/CTDirect.jl/pull/110)

**Comment by jbcaillau** [comment]
> [Done](https://github.com/control-toolbox/CTDirect.jl/pull/110)
> 
> Regarding the arguments for the grid, we currently have
> 
> * grid_size (integer) for uniform grid
> * time_grid (vector like) for explici grid
> * @ocots mentioned we could also have a function such as (t0,tf) -> grid
> 
> I think the best way is to have a single argument **time_disc** or something, whose type will be a union of the different possibilities

@PierreMartinon just posted in another issue (can't find it now 😅) that
- I prefer two named rags (more readable / user friendly)
-  we ought to check what the current standard in Julia is for such things

**Comment by jbcaillau** [comment]
Well, the two things are related and of interest for @rand-asswad example

> This one is the non-uniform grid, not the high order scheme. Are we sleepwriting @jbcaillau ? :D
