### ISSUE TITLE
Sparse usage (Jacobian, Hessian of the constraints)

### ISSUE THREAD

**Issue by ocots** [control-toolbox/CTDirect.jl#52]
Improve sparse usage (Jacobian, Hessian of the constraints) in the `CTDirect` package.
- [ ] use problem information from ipopt after initialization to check if the NLP is solved with sparse or plain matrices (check number of nonzero elements in Jacobian and Hessian versus problem dimensions) and print a message.
- [ ] check latest versions of the AD/NLP packages
- [ ] benchmark

**Comment by PierreMartinon** [comment]
At this point I think we'll need some profiling tools and set up performance tests.

**Comment by PierreMartinon** [comment]
This was added in ADNLPModels :+1:
