### ISSUE TITLE
Scalar outputs in solution

### ISSUE THREAD

**Issue by ocots** [control-toolbox/CTDirect.jl#55]
it seems that the optimal control is a vector even if the dimension is 1:

https://github.com/control-toolbox/FRUMAM/blob/237e6d984dd0b54115a0a9e680a8c4f47ecaf86d/goddard_indirect.jl#L106

**Comment by PierreMartinon** [comment]
The scalar / vector thing again :D On the todo list...

**Comment by PierreMartinon** [comment]
@cots If I'm not mistaken you already fixed this one in the solution.jl code ?

**Comment by ocots** [comment]
yes I think it is ok now.
