### ISSUE TITLE
Move functions

### ISSUE THREAD

**Issue by ocots** [control-toolbox/CTDirect.jl#7]
@PierreMartinon @joseph-gergaud Could you move the definitions of functions and structs from `CTDirect.jl` to another location: https://github.com/control-toolbox/CTDirect.jl/blob/e3fd356c375206ecce294c806e6c6fc2c0001b46/src/CTDirect.jl#L25

**Comment by PierreMartinon** [comment]
On peut certainement, mais pourquoi ?
  

  

  

  
  
  
  
  
>

**Comment by ocots** [comment]
Not a big deal. Just to be consistent with the other packages. The other main `.jl` files do not contain long pieces of code, to see clearly: 
- the `using / import`
- the `include`
- the `const` declarations 
- the `export`

**Comment by ocots** [comment]
See for instance, [CTFlows.jl](https://github.com/control-toolbox/CTFlows.jl/blob/main/src/CTFlows.jl):
```julia
module CTFlows

#
using OrdinaryDiffEq
import Base: *, isempty, Base
using CTBase
using Plots: plot, Plots
#
Base.isempty(p::OrdinaryDiffEq.SciMLBase.NullParameters) = true

# --------------------------------------------------------------------------------------------------
# Aliases for types
const CoTangent = MyVector
const Control = MyVector
const DState = MyVector
const DAdjoint = MyVector
const DCoTangent = MyVector

#
const ctgradient = CTBase.ctgradient

# --------------------------------------------------------------------------------------------
#
include("default.jl")
include("solutions.jl")
include("flows.jl")
include("constructors.jl")
#
include("hamiltonian.jl")
include("hamiltonian_vector_field.jl")
include("vector_field.jl")
include("optimal_control_problem.jl")
#
include("plot.jl")
include("concatenation.jl")

#
export isnonautonomous
export VectorField
export Hamiltonian
export HamiltonianVectorField
export Flow
export plot
export *

end
```

**Comment by PierreMartinon** [comment]
Done (see PR https://github.com/control-toolbox/CTDirect.jl/pull/8)
