### ISSUE TITLE
Extract from solve function the possibility to create an ADNLPModel

### ISSUE THREAD

**Issue by jbcaillau** [control-toolbox/CTDirect.jl#70]
@PierreMartinon @ocots Pierre, would be nice to extract the conversion from an `ocp` to an `nlp` of `ADNLPModel` type from the `solve` function:
https://github.com/control-toolbox/CTDirect.jl/blob/ef02151d8aa760f0cd1f4d42469ad9fa856a2466/src/solve.jl#L77

More generally, one might like to be able to do not only this

```julia
ocp = ... # functional / abstract description
sol = solve(ocp)
```

but also that (finer granularity):

```julia
ocp = ... # functional / abstract description
nlp = ADLNLPModel(ocp) # will, most likely, use CTBase.nlp_constraints
sol = solve(nlp)
```

Or, of course, use any solver NLP modeller / solver (see, *e.g.*, [MadNLP](https://madnlp.github.io/MadNLP.jl/dev/)), parametrising the `ocp -> nlp` arrow by the numerical scheme (RK, user provided, *etc.*)

# See also

[CTBase.nlp_constraints](https://control-toolbox.org/CTBase.jl/dev/api-model.html#CTBase.nlp_constraints-Tuple{OptimalControlModel})

**Comment by ocots** [comment]
When this will be done I propose to put the solve function directly inside OptimalControl package instead of CTDirect. Hence, CTDirect only makes the transcription.

**Comment by PierreMartinon** [comment]
Ok I'll get started on the export !

**Comment by ocots** [comment]
Isn't it better to have 
```julia
Bip = Direct(ocp, :adnlpmodel, scheme=rk4)
```

**Comment by PierreMartinon** [comment]
At first it will probably look like 
'''nlp = DirectTranscription(ocp, steps=100)'''

The NLP format and discretization scheme would be natural options indeed.

**Comment by jbcaillau** [comment]
@PierreMartinon @ocots both look fine to me

**Comment by PierreMartinon** [comment]
Done
