### ISSUE TITLE
Use MKL.jl

### ISSUE THREAD

**Issue by jbcaillau** [control-toolbox/CTDirect.jl#9]
@PierreMartinon @gergaud check email with @amontoison and @tmigot on this:
> Si vous utilisez Ipopt.jl, j'ai oublié de vous dire d'utiliser MKL avec `using MKL` si vous avez Julia >= 1.8 et un OS différent de Windows. J'ai précompilé Ipopt_jll et MUMPS_jll pour qu'ils utilisent LBT (libblastrampoline) et ça permet de changer dynamiquement le backend BLAS/LAPACK.

[MKL.jl](https://github.com/JuliaLinearAlgebra/MKL.jl)

To try and add in dependencies?

**Comment by amontoison** [comment]
Au niveau des dépendances on `NLPModelIpopt.jl -> Ipopt.jl -> Ipopt_jll.jl`.
Le Ipopt_jll que j'ai compilé pour Julia >= 1.8 permet d'utiliser le backend BLAS/LAPACK que l'utilisateur possède.
```julia
julia> using Ipopt
julia> BLAS.get_config()
LinearAlgebra.BLAS.LBTConfig
Libraries: 
├ [ILP64] libopenblas64_.so
└ [ LP64] libopenblas.so
```
```julia
julia> using MKL
julia> BLAS.get_config()
LinearAlgebra.BLAS.LBTConfig
Libraries: 
├ [ILP64] libmkl_rt.so
└ [ LP64] libmkl_rt.so
```

**Comment by jbcaillau** [comment]
Merci @amontoison ; je reproduis ci-dessous l'échange par mail précédent pour mémoire : dis moi si ça pose pb.

> Le dernier projet peut vous intéresser puisqu'il permet d'utiliser MA57 / MA97 à la place de MUMPS dans Ipopt.

>> Gain attendu / classe de problèmes visés ?

> MA57 c'est ce qui est utilisé par MATLAB pour le \ avec des matrices creuses
> sauf que MATLAB a acheté la licence pour la version de 2003.
> Entre temps il y a eu de nombreuses améliorations et des corrections de bug.
> C'est généralement plus rapide que tout le reste lorsqu'on lance Ipopt sur notre machine.
> C'est le top du top en solveur multi-threadé.

>> Oui, on utilise NLPModelsIpopt.jl (dans CTDirect.jl) qui utilise ensuite Ipopt.jl (sous Julia >= 1.8, en effet, et surtout pas sous windows). Sur ce point, deux questions :
>> - quel est le défaut : BLAS ou LAPACK ?
>> - avantages attendus de l'un vs. l'autre ?

> Julia est compilé avec OpenBLAS pour l'ensemble des plateformes disponibles (artifact OpenBLAS_jll). OpenBLAS propose une version multi-threadée de chaque fonction de BLAS et LAPACK.
Lorsque tu fais un produit scalaire ou un produit matrice-matrice dense en Julia, Julia appelle la routine
associé de OpenBLAS.
Depuis Julia v"1.6", on a LBT -- libblastrampoline (https://github.com/JuliaLinearAlgebra/libblastrampoline) qui
permet de changer dynamiquement la librairie qu'on va utiliser pour les appels à des fonctions de BLAS et LAPACK.
> Par défaut, il envoie les appels vers OpenBLAS.
>
> Tu peux le voir avec les commandes suivantes:
```
julia> using LinearAlgebra
julia> BLAS.get_config()
LinearAlgebra.BLAS.LBTConfig
Libraries:
└ [ILP64] libopenblas64_.so
```

```
julia> using MKL

julia> BLAS.get_config()
LinearAlgebra.BLAS.LBTConfig
Libraries:
├ [ILP64] libmkl_rt.so
└ [ LP64] libmkl_rt.so
```

> Pour MUMPS_jll et Ipopt_jll, j'ai compilé les artifacts avec LBT également. Ça permet d'avoir la même chose.
> Attention il y deux versions de BLAS/LAPACK (LP64 et ILP64), certains logiciels utilisent des entiers 64 bits (ILP64 -- SuiteSparse)
> alors que d'autres des entiers 32 bits (LP64 -- MUMPS, Ipopt).
> Lorsque tu utilises Ipopt.jl, tu as automatiquement un backend LP64 qui ajouté si tu n'en avais pas (OpenBLAS32_jll).

> L'avantage d'utiliser MKL, BLIS, AppleAccelerate, etc... par rapport à OpenBLAS est qu'on a parfois des backend BLAS/LAPACK plus performants
> pour notre architecture. Si tu as un processeur Intel, MKL est plus rapide que OpenBLAS je trouve.

**Comment by PierreMartinon** [comment]
Same as other performance topics. Time to set up some profiling and benchmarking :)

**Comment by amontoison** [comment]
@jbcaillau 
I recompiled Ipopt with better options (`-03`) and added a new linear solver (`SPRAL`).
If you use Julia 1.9 and the release 1.4.1 of Ipopt.jl, you will use it automatically after updating your packages.

Ipopt and the linear solvers (MUMPS, SPRAL or JuliaHSL) also use the BLAS and LAPACK backend that you want.

**Comment by jbcaillau** [comment]
@amontoison Thanks for the update. Do you mean '-O3'? OK for [SPRAL](https://www.numerical.rl.ac.uk/spral) (not aware of it). Yes, I am using Julia 1.9, checking about our packages version.

All in all, it would be nice to have a discussion with you, @PierreMartinon @ocots and @gergaud on performance issues. Up to now, we are using the packages in the most naive way, and it is probably time for some performance profiling. Any availability on your side within the end of June for a catch up? If i remember correctly, you will in Toulouse next week for the Sparse days?

**Comment by PierreMartinon** [comment]
See #69
